# Use Node.js Alpine image
FROM node:22-alpine

# Set working directory
WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

# Copy only package.json and package-lock.json to install deps
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app source code
COPY . .

# Copy the .env.dev file and rename it to .env (if your app reads .env by default)
COPY .env.prod .env

# Expose the port your dev server runs on
EXPOSE 5175

# Run the development server with host binding
CMD ["npm", "run", "dev", "--", "--host"]
