# Use Node.js Alpine image
FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

COPY .env.dev .env

RUN npm run build

# Create non-root user
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

# Change ownership of app directory
RUN chown -R nextjs:nextjs /app

USER nextjs

EXPOSE 5175

# CMD ["npm", "run", "dev", "--", "--host", "--port", "5175"]
CMD ["npm", "start"]
