# Use Node.js Alpine image
FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

COPY .env.dev .env

RUN npm run build

EXPOSE 5175

# CMD ["npm", "run", "dev", "--", "--host", "--port", "5175"]
CMD ["npm", "start", "-p", "5175"]