/**
 * Document type enum matching backend Java enum
 */
export enum DocumentType {
  // Identity Documents
  ID_CARD = "ID_CARD",
  PASSPORT = "PASSPORT",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE",
  NID_SELFIE = "NID_SELFIE",

  // Profile & Branding Documents
  PROFILE_PICTURE = "PROFILE_PICTURE",
  COVER_PHOTO = "COVER_PHOTO",
  LOGO = "LOGO",
  BANNER = "BANNER",
  GALLERY_IMAGE = "GALLERY_IMAGE",

  // Doctor Documents
  PROFESSIONAL_LICENSE = "PROFESSIONAL_LICENSE",
  BOARD_CERTIFICATION = "BOARD_CERTIFICATION",
  EDUCATIONAL_CERTIFICATE = "EDUCATIONAL_CERTIFICATE",
  CONTINUING_EDUCATION = "CONTINUING_EDUCATION",
  EMPLOYMENT_CONTRACT = "EMPLOYMENT_CONTRACT",
  DOCTOR_SIGNATURE = "DOCTOR_SIGNATURE",
  PRESCRIPTION_PAD_TEMPLATE = "PRESCRIPTION_PAD_TEMPLATE",
  DOCTOR_BLOG_IMAGE = "DOCTOR_BLOG_IMAGE",

  // Nurse Documents
  NURSING_LICENSE = "NURSING_LICENSE",
  NURSING_CERTIFICATE = "NURSING_CERTIFICATE",
  TRAINING_CERTIFICATE = "TRAINING_CERTIFICATE",
  EXPERIENCE_CERTIFICATE = "EXPERIENCE_CERTIFICATE",
  HOME_CARE_CERTIFICATION = "HOME_CARE_CERTIFICATION",

  // Legal & Verification
  POLICE_CLEARANCE = "POLICE_CLEARANCE",
  BACKGROUND_CHECK = "BACKGROUND_CHECK",
  WORK_PERMIT = "WORK_PERMIT",
  RESIDENCY_PERMIT = "RESIDENCY_PERMIT",
  TAX_IDENTIFICATION = "TAX_IDENTIFICATION",

  // Hospital / Institute Documents
  HOSPITAL_LICENSE = "HOSPITAL_LICENSE",
  HOSPITAL_REGISTRATION = "HOSPITAL_REGISTRATION",
  HOSPITAL_FIRE_CERTIFICATE = "HOSPITAL_FIRE_CERTIFICATE",
  DEPARTMENT_IMAGE = "DEPARTMENT_IMAGE",
  AMENITY_IMAGE = "AMENITY_IMAGE",
  TEST_PRICE_SHEET = "TEST_PRICE_SHEET",
  TEST_BROCHURE = "TEST_BROCHURE",

  // Medical & Patient Documents
  MEDICAL_REPORT = "MEDICAL_REPORT",
  PRESCRIPTION = "PRESCRIPTION",
  LAB_TEST_RESULT = "LAB_TEST_RESULT",
  IMAGING_RESULT = "IMAGING_RESULT",
  VACCINATION_RECORD = "VACCINATION_RECORD",
  MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE",
  DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY",
  OPD_SLIP = "OPD_SLIP",
  CLINICAL_NOTES = "CLINICAL_NOTES",
  CARE_SESSION_REPORT = "CARE_SESSION_REPORT",
  DIAGNOSIS_DOCUMENT = "DIAGNOSIS_DOCUMENT",
  PATIENT_INSURANCE_DOCUMENT = "PATIENT_INSURANCE_DOCUMENT",
  PATIENT_PROFILE_PICTURE = "PATIENT_PROFILE_PICTURE",

  // Fundraising Documents
  FUNDRAISING_PATIENT_DOCUMENT = "FUNDRAISING_PATIENT_DOCUMENT",
  HOSPITAL_ESTIMATED_BILL = "HOSPITAL_ESTIMATED_BILL",
  TREATMENT_PLAN = "TREATMENT_PLAN",
  BENEFICIARY_NID = "BENEFICIARY_NID",
  DONATION_REPORT_ATTACHMENT = "DONATION_REPORT_ATTACHMENT",

  // Advertisement Documents
  AD_IMAGE = "AD_IMAGE",
  AD_VIDEO = "AD_VIDEO",
  AD_POPUP_IMAGE = "AD_POPUP_IMAGE",

  // Payment & Financial
  INVOICE = "INVOICE",
  RECEIPT = "RECEIPT",
  PAYMENT_PROOF = "PAYMENT_PROOF",
  CONTRACT_DOCUMENT = "CONTRACT_DOCUMENT",
  POLICY_DOCUMENT = "POLICY_DOCUMENT",
  TOS_DOCUMENT = "TOS_DOCUMENT",

  // Insurance Documents
  INSURANCE_CARD = "INSURANCE_CARD",
  MALPRACTICE_INSURANCE = "MALPRACTICE_INSURANCE",

  // Media Files
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  AUDIO = "AUDIO",

  // System & Export Files
  EXPORT_CSV = "EXPORT_CSV",
  EXPORT_PDF = "EXPORT_PDF",
  BACKUP_FILE = "BACKUP_FILE",

  // General
  CERTIFICATE = "CERTIFICATE",
  OTHER = "OTHER",
}

/**
 * File upload response from server
 */
export interface FileUploadResponse {
  photoUrl: string;
  presignedUrl: string;
}

/**
 * Document type metadata
 */
export interface DocumentTypeInfo {
  value: DocumentType;
  displayName: string;
  banglaName: string;
  category: string;
}
