export interface HealthVitals {
  id: number;
  bmi: number | null;
  pulsePressure: number | null;
  cardiacOutput: number | null;
  respiratoryRate: number | null;
  oxygenSaturation: number | null;
  peakFlowRate: number | null;
  forcedVitalCapacity: number | null;
  temperatureCelsius: number | null;
  temperatureSite: string | null;
  basalMetabolicRate: number | null;
  bloodGlucoseMgDl: number | null;
  bloodGlucoseMmolL: number | null;
  hoursSinceLastMeal: number | null;
  bodyFatPercentage: number | null;
  muscleMassKg: number | null;
  hipCircumferenceCm: number | null;
  waistHipRatio: number | null;
  neckCircumferenceCm: number | null;
  visceralFatLevel: number | null;
  fluidIntakeMl24h: number | null;
  urineOutputMl24h: number | null;
  painScale0To10: number | null;
  painLocation: string | null;
  sleepHoursLastNight: number | null;
  sleepQuality1To5: number | null;
  activeMinutes24h: number | null;
  caloriesBurned24h: number | null;
  stressLevel1To10: number | null;
  moodScore1To10: number | null;
  anxietyLevel1To10: number | null;
  cortisolLevel: number | null;
  vitaminDLevel: number | null;
  hemoglobinLevel: number | null;
  whiteBloodCellCount: number | null;
  cholesterolTotal: number | null;
  cholesterolLdl: number | null;
  cholesterolHdl: number | null;
  triglycerides: number | null;
  measurementMethod: string | null;
  measurementDevice: string | null;
  measurementLocation: string | null;
  measurementPosition: string | null;
  measurementAccuracy: string | null;
  overallHealthScore: number | null;
  fitnessLevel: string | null;
  healthAlerts: string | null;
  medicationsTaken: string | null;
  recentExercise: boolean | null;
  recentCaffeine: boolean | null;
  recentAlcohol: boolean | null;
  recentSmoking: boolean | null;
  menstrualCycleDay: number | null;
  followUpRequired: boolean;
  followUpPriority: string | null;
  createdBy: string;
  createdAt: string;
  updatedBy: string;
  updatedAt: string;
  isLowOxygen: boolean;
  isFever: boolean;
  isObesity: boolean;
  tcHdlRatio: number | null;
  profileId: number;
  recordedAt: string;
  heartRate: number | null;
  ketones: number | null;
  heightCm: number | null;
  weightKg: number | null;
  boneDensity: number | null;
  painType: string | null;
  steps24h: number | null;
  symptoms: string | null;
  notes: string | null;
  daysSinceLastRecording: number;
  isFullMetabolicPanel: boolean;
  isRecentContextKnown: boolean | null;
  isObstructiveLungDisease: boolean;
  bloodPressureSystolic: number | null;
  bloodPressureDiastolic: number | null;
  meanArterialPressure: number | null;
  heartRateVariability: number | null;
  forcedExpiratoryVolume: number | null;
  restingEnergyExpenditure: number | null;
  glucoseMeasurementType: string | null;
  waistCircumferenceCm: number | null;
  hydrationLevelPercentage: number | null;
  urineSpecificGravity: number | null;
  environmentalTemperature: number | null;
  environmentalHumidity: number | null;
  cardiovascularRiskScore: number | null;
  metabolicHealthScore: number | null;
  bloodPressureStatus: string;
  isWidePulsePressure: boolean;
  isTachycardia: boolean;
  isBradycardia: boolean;
  isHypothermia: boolean;
  isHyperglycemia: boolean;
  isHypoglycemia: boolean;
  isUnderweight: boolean;
  isIsolatedSystolicHypertension: boolean;
}
