name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:
  build:
    name: Install & Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build for Production
        run: npm run build

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Environment Name
        id: env_name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENV_NAME=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile.${{ env.ENV_NAME }} -t ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-latest \
            ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-${{ github.sha }}

          docker push ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-latest
          docker push ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-${{ github.sha }}

  deploy:
    name: Deploy Frontend to Server
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/dev'  # 🔹 Only for dev, expand if needed
    steps:
      - name: Determine Environment Name
        id: env_name
        run: echo "ENV_NAME=dev" >> $GITHUB_ENV

      - name: SSH and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-latest
            sudo docker stop open-care-frontend || true
            sudo docker rm open-care-frontend || true
            sudo docker system prune -af
            sudo docker run -d --name open-care-frontend -p 5175:5173 --restart always \
              --env-file /home/alwyzon/open-care-frontend/.env.${{ env.ENV_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/open-care-frontend:${{ env.ENV_NAME }}-latest
